export const DEFAULT_DELAY = 1500;
export const languageLogos: { [key: string]: string } = {
    'JavaScript': 'https://cdn.simpleicons.org/javascript/F7DF1E',
    'TypeScript': 'https://cdn.simpleicons.org/typescript/3178C6',
    'Python': 'https://cdn.simpleicons.org/python/3776AB',
    'Java': 'https://cdn.simpleicons.org/openjdk/007396',
    'HTML': 'https://cdn.simpleicons.org/html5/E34F26',
    'CSS': 'https://cdn.simpleicons.org/css3/1572B6',
    'Ruby': 'https://cdn.simpleicons.org/ruby/CC342D',
    'Go': 'https://cdn.simpleicons.org/go/00ADD8',
    'Rust': 'https://cdn.simpleicons.org/rust/000000',
    'Swift': 'https://cdn.simpleicons.org/swift/FA7343',
    'Kotlin': 'https://cdn.simpleicons.org/kotlin/0095D5',
    'C++': 'https://cdn.simpleicons.org/cplusplus/00599C',
    'C#': 'https://cdn.simpleicons.org/csharp/239120',
    'PHP': 'https://cdn.simpleicons.org/php/777BB3',
    'Scala': 'https://cdn.simpleicons.org/scala/DC322F',
    'Dart': 'https://cdn.simpleicons.org/dart/0175C2',
    'Lua': 'https://cdn.simpleicons.org/lua/00007C',
    'Haskell': 'https://cdn.simpleicons.org/haskell/5D4F7C',
    'Elixir': 'https://cdn.simpleicons.org/elixir/4B275F',
    'Perl': 'https://cdn.simpleicons.org/perl/39457E',

    'React': 'https://cdn.simpleicons.org/react/61DAFB',
    'Vue': 'https://cdn.simpleicons.org/vuedotjs/4FC08D',
    'Angular': 'https://cdn.simpleicons.org/angular/DD0031',
    'Node.js': 'https://cdn.simpleicons.org/nodedotjs/339933',
    'Django': 'https://cdn.simpleicons.org/django/092E20',
    'Flask': 'https://cdn.simpleicons.org/flask/000000',
    'Spring': 'https://cdn.simpleicons.org/spring/6DB33F',
    'Laravel': 'https://cdn.simpleicons.org/laravel/FF2D20',
    'Express': 'https://cdn.simpleicons.org/express/000000',
    'Svelte': 'https://cdn.simpleicons.org/svelte/FF3E00',
    'Nest.js': 'https://cdn.simpleicons.org/nestjs/E0234E',
    'Tensorflow': 'https://cdn.simpleicons.org/tensorflow/FF6F00',
    'PyTorch': 'https://cdn.simpleicons.org/pytorch/EE4C2C',

    'MySQL': 'https://cdn.simpleicons.org/mysql/4479A1',
    'PostgreSQL': 'https://cdn.simpleicons.org/postgresql/4169E1',
    'MongoDB': 'https://cdn.simpleicons.org/mongodb/47A248',
    'Redis': 'https://cdn.simpleicons.org/redis/DC382D',
    'SQLite': 'https://cdn.simpleicons.org/sqlite/003B57',

    'Docker': 'https://cdn.simpleicons.org/docker/2496ED',
    'Kubernetes': 'https://cdn.simpleicons.org/kubernetes/326CE5',
    'AWS': 'https://cdn.simpleicons.org/amazonaws/232F3E',
    'Google Cloud': 'https://cdn.simpleicons.org/googlecloud/4285F4',
    'Azure': 'https://cdn.simpleicons.org/microsoftazure/0078D4',
    'default': 'https://cdn.simpleicons.org/github/181717'
};